language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak/quickstarts

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx2048m"

before_install:
  - git clone https://github.com/keycloak/keycloak.git > /dev/null 2>&1 && cd keycloak
  - mvn clean install -s ../settings-snapshots.xml --no-snapshot-updates -Pdistribution -DskipTests=true -B -V -q
  - mkdir ../keycloak-server && tar xzf distribution/server-dist/target/keycloak-3.1.0.CR1-SNAPSHOT.tar.gz -C ../keycloak-server --strip-components 1
  - cd .. && scripts/start-server.sh

install:
  - mvn clean install -s settings-snapshots.xml -Pwildfly-managed -Denforcer.skip=true

script:
  - mvn -s settings-snapshots.xml -Pwildfly-managed -Denforcer.skip=true clean verify -q

after_install:
  - ./scripts/stop-server.sh
  - kill -9 `cat pid.txt`

sudo: false
